[package]
name = "steam-tradeoffer-manager"
version = "0.1.0"
edition = "2021"
description = "Makes steam trade offers easy."
authors = ["Julia"]
homepage = "https://github.com/juliarose/steam-tradeoffer-manager"
repository = "https://github.com/juliarose/steam-tradeoffer-manager"
license = "MIT"
keywords = ["tf2", "steam"]
readme = "README.md"
exclude = ["/assets", "/examples", ".*"]

[dependencies]
reqwest = { version = "0.11", features = ["json", "cookies"] }
reqwest-middleware = "0.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = { version = "1.0", features = ["raw_value"] }
serde_repr = "0.1"
serde_qs = "0.8"
tokio = { version = "1", features = ["rt"] }
strum = { version = "0.23.0", features = ["derive"] }
strum_macros = "0.23.0"
chrono = { version = "0.4.0", features = ["serde"] }
steamid-ng = "1.0"
num_enum = "0.5.0"
anyhow = "1.0"
lazy-regex = "2.2.0"
async-fs = "1.5.0"
futures = "0.3.0"
url = "2.2.0"
lfu_cache = "1.2.1"
scraper = "0.12.0"
thiserror = "1.0.30"
log = "0.4.0"
async-std = "1.12.0"
unescape = "0.1.0"
rand = "0.8"
another-steam-totp = { version = "0.2.0", features = ["reqwest"] }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"
criterion = "0.3"

[[bench]]
name = "trade_offer_mapping"
harness = false

[[bench]]
name = "deserialize"
harness = false