[package]
name = "steam-tradeoffers"
version = "0.1.0"
edition = "2021"
description = "Makes steam trade offers easy."
authors = ["Julia"]
homepage = "https://github.com/juliarose/steam-tradeoffers"
repository = "https://github.com/juliarose/steam-tradeoffers"
license = "MIT"
keywords = ["tf2", "steam"]
readme = "README.md"

[dependencies]
reqwest = { version = "^0.11.7", features = ["json", "cookies"] }
reqwest-retry = "0.1.3"
reqwest-middleware = "0.1.2"
serde = { version = "^1.0", features = ["derive", "rc"] }
serde_json = { version = "^1.0", features = ["raw_value"] }
serde_repr = "0.1"
serde_qs = "0.8.5"
tokio = { version = "^1", features = ["rt"] }
strum = { version = "0.23", features = ["derive"] }
strum_macros = "0.23"
chrono = { version = "0.4", features = ["serde"] }
steamid-ng = "1.0.0"
num_enum = "0.5.5"
anyhow = "1.0.44"
lazy-regex = "2.2.2"
async-std = "1.10.0"
itertools = "0.10.3"
async-fs = "1.5.0"
futures-lite = "1.12.0"
futures = "0.3.19"
bytes = "1.1.0"
url = "2.2.2"
lfu_cache = "1.2.1"
base64 = "0.13.0"
hmac-sha1 = "^0.1"
sha-1 = "0.10.0"
scraper = "0.12.0"
thiserror = "^1.0.30"
log = "0.4"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
dotenv = "0.15.0"