[package]
name = "steam-tradeoffers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.7", features = ["json", "cookies"] }
reqwest-retry = "0.1.3"
reqwest-middleware = "0.1.2"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_with = "1.11.0"
serde_repr = "0.1"
serde_qs = "0.8.5"
tokio = { version = "1", features = ["full"] }
tokio-test = "0.4.2"
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
strum = { version = "0.23", features = ["derive"] }
strum_macros = "0.23"
chrono = { version = "0.4", features = ["serde"] }
steamid-ng = "1.0.0"
num_enum = "0.5.5"
anyhow = "1.0.44"
lazy-regex = "2.2.2"
async-recursion = "1.0.0"
async-std = "1.10.0"
itertools = "0.10.3"
deepsize = "0.2.0"
async-fs = "1.5.0"
futures-lite = "1.12.0"
futures = "0.3.19"
bytes = "1.1.0"